[package]
name = "rust-wasm-attractor"
version = "1.0.0"
authors = ["dmaynard <davidsmaynard@gmail.com>"]
edition = "2021"
description = "Chaotic Attractor Loop in Rust -> WASM -> Module" 
repository ="git@github.com:dmaynard/rust-wasm-attractor.git"
license="MIT"


[lib]
crate-type = ["cdylib", "rlib"]


[dependencies]
js-sys = "0.3"
wasm-bindgen = "0.2.80"
humantime = "2"

[dependencies.web-sys]
version = "0.3.4"
features = ["console", 'Window', 'Performance', 'PerformanceTiming']

# The `console_error_panic_hook` crate provides better debugging of panics by
# logging them with `console.error`. This is great for development, but requires
# all the `std::fmt` and `std::panicking` infrastructure, so isn't great for
# code size when deploying.
# console_error_panic_hook = { version = "0.1.6", optional = true }

# `wee_alloc` is a tiny allocator for wasm that is only ~1K in code size
# compared to the default allocator's ~10K. It is slower than the default
# allocator, however.
#
# Unfortunately, `wee_alloc` requires nightly Rust when targeting wasm for now.
# wee_alloc = { version = "0.4.5", optional = true }

[dev-dependencies]
wasm-bindgen-test = "0.3.13"

[profile.release]
# Tell `rustc` to optimize for speed.
opt-level = 3
